description: 'The Swagger UI app renders a documentation based on the OpenAPI specification.'
screenshot: 'https://www.fusio-project.org/media/apps/swagger-ui.png'
website: 'https://github.com/apioo/fusio-apps-swaggerui'